from __future__ import annotations

from contextlib import contextmanager
from typing import Iterator

import psycopg2
from psycopg2.extensions import connection as PgConnection

from config.settings import POSTGRES_CONFIG


DB_SCHEMA = "core"
LOG_SCHEMA = "logs"


def get_db_connection() -> PgConnection:
    return psycopg2.connect(**POSTGRES_CONFIG)


@contextmanager
def db_connection() -> Iterator[PgConnection]:
    conn = get_db_connection()
    try:
        yield conn
    finally:
        conn.close()


def ensure_schema() -> None:
    statements = (
        """
        CREATE SCHEMA IF NOT EXISTS core;
        """,
        """
        CREATE SCHEMA IF NOT EXISTS logs;
        """,
        """
        CREATE TABLE IF NOT EXISTS core.stations (
            id SERIAL PRIMARY KEY,
            station_name VARCHAR(255) NOT NULL,
            location VARCHAR(255),
            charger_count INTEGER NOT NULL,
            status VARCHAR(30) NOT NULL DEFAULT 'online'
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS core.users (
            id SERIAL PRIMARY KEY,
            username VARCHAR(255) NOT NULL,
            vehicle_id VARCHAR(100) NOT NULL,
            priority_level INTEGER NOT NULL DEFAULT 1
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS core.reservations (
            id SERIAL PRIMARY KEY,
            user_id INTEGER REFERENCES core.users(id) ON DELETE SET NULL,
            station_id INTEGER NOT NULL REFERENCES core.stations(id) ON DELETE CASCADE,
            charger_id INTEGER NOT NULL,
            reservation_start TIMESTAMPTZ NOT NULL,
            reservation_end TIMESTAMPTZ NOT NULL,
            reservation_status VARCHAR(30) NOT NULL DEFAULT 'reserved',
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT reservations_valid_window CHECK (reservation_end > reservation_start)
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS core.charging_sessions (
            id SERIAL PRIMARY KEY,
            reservation_id INTEGER REFERENCES core.reservations(id) ON DELETE SET NULL,
            station_id INTEGER NOT NULL REFERENCES core.stations(id) ON DELETE CASCADE,
            charger_id INTEGER NOT NULL,
            vehicle_id VARCHAR(100) NOT NULL,
            session_start TIMESTAMPTZ NOT NULL,
            session_end TIMESTAMPTZ,
            session_status VARCHAR(30) NOT NULL DEFAULT 'charging'
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS logs.station_events (
            id SERIAL PRIMARY KEY,
            station_id INTEGER REFERENCES core.stations(id) ON DELETE SET NULL,
            vehicle_id VARCHAR(100),
            event_type VARCHAR(80) NOT NULL,
            event_message TEXT NOT NULL,
            event_timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        """,
    )

    with db_connection() as conn:
        with conn.cursor() as cur:
            for statement in statements:
                cur.execute(statement)
            migrations = (
                "ALTER TABLE core.reservations DROP CONSTRAINT IF EXISTS reservations_slot_id_fkey;",
                "ALTER TABLE core.reservations DROP CONSTRAINT IF EXISTS reservations_vehicle_id_fkey;",
                "ALTER TABLE core.reservations DROP CONSTRAINT IF EXISTS reservations_point_id_fkey;",
                "ALTER TABLE core.reservations DROP CONSTRAINT IF EXISTS fk_point;",
                "ALTER TABLE core.reservations DROP CONSTRAINT IF EXISTS fk_time_window;",
                "ALTER TABLE core.charging_sessions DROP CONSTRAINT IF EXISTS charging_sessions_point_id_fkey;",
                "ALTER TABLE core.charging_sessions DROP CONSTRAINT IF EXISTS fk_session_point;",
                "ALTER TABLE core.stations ADD COLUMN IF NOT EXISTS id INTEGER GENERATED BY DEFAULT AS IDENTITY;",
                "ALTER TABLE core.stations ADD COLUMN IF NOT EXISTS station_name VARCHAR(255);",
                "ALTER TABLE core.stations ADD COLUMN IF NOT EXISTS charger_count INTEGER;",
                "ALTER TABLE core.users ADD COLUMN IF NOT EXISTS id INTEGER GENERATED BY DEFAULT AS IDENTITY;",
                "ALTER TABLE core.users ADD COLUMN IF NOT EXISTS username VARCHAR(255);",
                "ALTER TABLE core.users ADD COLUMN IF NOT EXISTS vehicle_id VARCHAR(100);",
                "ALTER TABLE core.users ADD COLUMN IF NOT EXISTS priority_level INTEGER DEFAULT 1;",
                "ALTER TABLE core.reservations ADD COLUMN IF NOT EXISTS id INTEGER GENERATED BY DEFAULT AS IDENTITY;",
                "ALTER TABLE core.reservations ADD COLUMN IF NOT EXISTS user_id INTEGER;",
                "ALTER TABLE core.reservations ADD COLUMN IF NOT EXISTS charger_id INTEGER;",
                "ALTER TABLE core.reservations ADD COLUMN IF NOT EXISTS reservation_start TIMESTAMPTZ;",
                "ALTER TABLE core.reservations ADD COLUMN IF NOT EXISTS reservation_end TIMESTAMPTZ;",
                "ALTER TABLE core.reservations ADD COLUMN IF NOT EXISTS reservation_status VARCHAR(30) DEFAULT 'reserved';",
                "ALTER TABLE core.reservations ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;",
                "ALTER TABLE core.charging_sessions ADD COLUMN IF NOT EXISTS id INTEGER GENERATED BY DEFAULT AS IDENTITY;",
                "ALTER TABLE core.charging_sessions ADD COLUMN IF NOT EXISTS charger_id INTEGER;",
                "ALTER TABLE core.charging_sessions ADD COLUMN IF NOT EXISTS vehicle_id VARCHAR(100);",
                "ALTER TABLE core.charging_sessions ADD COLUMN IF NOT EXISTS session_start TIMESTAMPTZ;",
                "ALTER TABLE core.charging_sessions ADD COLUMN IF NOT EXISTS session_end TIMESTAMPTZ;",
                "ALTER TABLE core.charging_sessions ADD COLUMN IF NOT EXISTS session_status VARCHAR(30) DEFAULT 'charging';",
                "ALTER TABLE logs.station_events ADD COLUMN IF NOT EXISTS id INTEGER GENERATED BY DEFAULT AS IDENTITY;",
                "ALTER TABLE logs.station_events ADD COLUMN IF NOT EXISTS vehicle_id VARCHAR(100);",
                "ALTER TABLE logs.station_events ADD COLUMN IF NOT EXISTS event_message TEXT;",
                "ALTER TABLE logs.station_events ADD COLUMN IF NOT EXISTS event_timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;",
            )
            for migration in migrations:
                cur.execute(migration)
            cur.execute(
                """
                UPDATE core.stations
                SET id = COALESCE(id, station_id),
                    name = COALESCE(name, station_name, CONCAT('Station ', station_id)),
                    station_name = COALESCE(station_name, name, CONCAT('Station ', station_id)),
                    total_slots = COALESCE(total_slots, charger_count, 1),
                    charger_count = COALESCE(charger_count, total_slots, 1)
                WHERE id IS NULL OR name IS NULL OR station_name IS NULL OR total_slots IS NULL OR charger_count IS NULL;
                """
            )
            cur.execute(
                """
                UPDATE core.users
                SET id = COALESCE(id, user_id),
                    username = COALESCE(username, name, CONCAT('user-', user_id)),
                    vehicle_id = COALESCE(vehicle_id, CONCAT('EV-', user_id)),
                    priority_level = COALESCE(priority_level, 1)
                WHERE id IS NULL OR username IS NULL OR vehicle_id IS NULL OR priority_level IS NULL;
                """
            )
            cur.execute(
                """
                UPDATE core.reservations
                SET id = COALESCE(id, reservation_id),
                    charger_id = COALESCE(charger_id, point_id, slot_id, 1),
                    reservation_start = COALESCE(reservation_start, scheduled_start, reserved_at, CURRENT_TIMESTAMP),
                    reservation_end = COALESCE(reservation_end, scheduled_end, expires_at, CURRENT_TIMESTAMP + INTERVAL '30 minutes'),
                    reservation_status = COALESCE(reservation_status, booking_status, status, 'reserved'),
                    created_at = COALESCE(created_at, reserved_at, CURRENT_TIMESTAMP)
                WHERE id IS NULL
                   OR charger_id IS NULL
                   OR reservation_start IS NULL
                   OR reservation_end IS NULL
                   OR reservation_status IS NULL
                   OR created_at IS NULL;
                """
            )
            cur.execute(
                """
                UPDATE core.charging_sessions
                SET id = COALESCE(id, session_id),
                    charger_id = COALESCE(charger_id, point_id, 1),
                    vehicle_id = COALESCE(vehicle_id, CONCAT('EV-', reservation_id)),
                    session_start = COALESCE(session_start, started_at, CURRENT_TIMESTAMP),
                    session_end = COALESCE(session_end, ended_at),
                    session_status = COALESCE(session_status, status, 'charging')
                WHERE id IS NULL
                   OR charger_id IS NULL
                   OR vehicle_id IS NULL
                   OR session_start IS NULL
                   OR session_status IS NULL;
                """
            )
            cur.execute(
                """
                UPDATE logs.station_events
                SET id = COALESCE(id, event_id),
                    event_message = COALESCE(event_message, event_type, 'station event'),
                    event_timestamp = COALESCE(event_timestamp, created_at, CURRENT_TIMESTAMP)
                WHERE id IS NULL OR event_message IS NULL OR event_timestamp IS NULL;
                """
            )
            cur.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_reservations_station_charger_window
                ON core.reservations (station_id, charger_id, reservation_start, reservation_end)
                WHERE reservation_status IN ('reserved', 'waiting', 'charging');
                """
            )
            cur.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_sessions_active
                ON core.charging_sessions (station_id, charger_id, session_status);
                """
            )
            cur.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_station_events_timestamp
                ON logs.station_events (event_timestamp DESC);
                """
            )
            cur.execute(
                """
                INSERT INTO core.stations (id, name, station_name, location, charger_count, total_slots, status)
                SELECT id, station_name, station_name, location, charger_count, charger_count, status
                FROM (
                    VALUES
                        (1, 'Station A', 'North coordination zone', 6, 'online'),
                        (2, 'Station B', 'Central coordination zone', 8, 'online'),
                        (3, 'Station C', 'South coordination zone', 10, 'online')
                ) AS seed(id, station_name, location, charger_count, status)
                WHERE NOT EXISTS (SELECT 1 FROM core.stations);
                """
            )
            cur.execute(
                """
                UPDATE core.stations
                SET charger_count = CASE id WHEN 1 THEN 6 WHEN 2 THEN 8 WHEN 3 THEN 10 ELSE charger_count END,
                    total_slots = CASE id WHEN 1 THEN 6 WHEN 2 THEN 8 WHEN 3 THEN 10 ELSE total_slots END,
                    name = CASE id WHEN 1 THEN 'Station A' WHEN 2 THEN 'Station B' WHEN 3 THEN 'Station C' ELSE name END,
                    station_name = CASE id WHEN 1 THEN 'Station A' WHEN 2 THEN 'Station B' WHEN 3 THEN 'Station C' ELSE station_name END
                WHERE id IN (1, 2, 3);
                """
            )
            cur.execute(
                """
                SELECT setval(
                    pg_get_serial_sequence('core.stations', 'id'),
                    COALESCE((SELECT MAX(id) FROM core.stations), 1),
                    true
                );
                """
            )
        conn.commit()


def ensure_indexes() -> None:
    ensure_schema()
